### ISSUE TITLE
Search typeahead dropdown misaligned (iphone/chrome)

### ISSUE THREAD

**Issue by jaimemarijke** [thatneat/climbplan#35]
The typeahead dropdown on the intro search page renders over the search box itself instead of below it

**Comment by jason-curtis** [comment]
possibly related issue, in any browser:
on the results page in particular, the dropdown does not seem to do well with page scrolling or resizing. repro:
1. make your window fairly wide
2. type something in on the results page so that the dropdown appears
3. without losing focus on the search box, scroll down/make your window narrower
expected: dropdown stays attached to the search box
actual: dropdown stays fixed w.r.t. the whole window, and does not get narrower when the window gets narrower

**Comment by jason-curtis** [comment]
see reactjs/react-autocomplete#166
one solution could be to use a more mature library such as http://react-autosuggest.js.org/
